### ISSUE TITLE
error Maximum update depth exceeded when scrolling dynamic grid

### ISSUE THREAD

**Issue by oss-susanta** [tannerlinsley/react-virtual#5] opened 2020-05-08 17:43 UTC
Steps:
1. Open https://codesandbox.io/s/github/tannerlinsley/react-virtual/tree/master/examples/sandbox
2. Select option "Dynamic"
3. In Grid Example, scroll to the bottom and back to the top. You will see this exception thrown:

![image](https://user-images.githubusercontent.com/65037002/81433002-80723b00-9181-11ea-9532-7248afae17b3.png)

Please find the recording:

[tannerlinsleyreact-virtual_ sandbox - CodeSandbox.webm.zip](https://github.com/tannerlinsley/react-virtual/files/4600619/tannerlinsleyreact-virtual_.sandbox.-.CodeSandbox.webm.zip)

**Comment by tannerlinsley** [comment] 2020-05-09 06:11
Hmm... I'm definitely seeing this on codesandbox, but only on the grid virtualizer, not the other two.

Another interesting tidbit is that if you run the example locally (not in codesandbox) or in prod, this issue doesn't exist. Very strange.

**Comment by tannerlinsley** [comment] 2020-05-09 06:12
I'm going to work on figuring out why this is happening in CS, but since I can't reproduce in production, going to close this for now.

**Closed by tannerlinsley** 2020-05-09 06:12 UTC
