### ISSUE TITLE
scrollTop / scrollLeft alignment for better scroll performance

### ISSUE THREAD

**Issue by meowtec** [tannerlinsley/react-virtual#242] opened 2022-01-10 10:50 UTC
The component will re-render every time when a scroll event trigger and `scrollOffset` updated. Although that is usually unnecessary.

May we could have an option **alignmentSize** to make the `scrollOffset` update by step:

```
const alignmentToBlock = (value, blockSize) =>
  blockSize == null ? value : Math.round(value / blockSize) * blockSize

// scrollOffset be 0 -> alignmentSize -> alignmentSize*2 -> alignmentSize*3
const [scrollOffset, setScrollOffset] = React.useState(0)

const onScroll = () => {
    setScrollOffset(alignmentToBlock(element[scrollKey], alignmentSize))
}
```

Using **alignmentSize** + `overscan` could avoid most unnecessary re-render.

See [the demo](https://codesandbox.io/s/react-playground-forked-uk54v?file=/index.js)

**Comment by piecyk** [comment] 2022-01-14 13:59
> Although that is usually unnecessary.

Yes, that is true. Duplicate of #237

**Comment by tannerlinsley** [comment] 2022-01-20 16:11
Tracking in #237

**Closed by tannerlinsley** 2022-01-20 16:11 UTC
